export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  NOT_FOUND = 'NOT_FOUND',
  UNSUPPORTED_CURRENCY = 'UNSUPPORTED_CURRENCY',
  RATE_NOT_AVAILABLE = 'RATE_NOT_AVAILABLE',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  RATES_UNAVAILABLE = 'RATES_UNAVAILABLE',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
